version: "3.7"

networks:
  condotec:
    name: condotec-network
    external: true

services:
  condotec_identity:
    container_name: condotec_identity
    build:
      context: .
      dockerfile: Dockerfile
    image: condotec_identity:${APP_VERSION}
    environment:
      - APP_VERSION=${APP_VERSION}
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - 8083:8080
    networks:
      - condotec

  condotec-sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    networks:
      - condotec
    environment:
      SA_PASSWORD: "Docker@2024"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - sqlsystem:/var/opt/mssql/
      - sqldata:/var/opt/sqlserver/data
      - sqllog:/var/opt/sqlserver/log
      - sqlbackup:/var/opt/sqlserver/backup

volumes:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup:
