version: "3.7"

networks:
  condotec:
    external:
      name: condotec-network

services:
    condotec_identity:
      container_name: condotec_identity
      build:
        context: .
        dockerfile: Dockerfile
      image: condotec_identity:${APP_VERSION}
      environment:
        - APP_VERSION=${APP_VERSION}
        - ASPNETCORE_ENVIRONMENT=Docker
      ports:
        - 8083:8080
      networks:
        - condotec