version: "3.7"

networks:
  condotec:
    name: condotec-network
    external: true

services:
  condotec_management:
    container_name: condotec_management
    build:
      context: .
      dockerfile: Dockerfile
    image: condotec_management:${APP_VERSION}
    environment:
      - APP_VERSION=${APP_VERSION}
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - 8084:8080
    networks:
      - condotec
